[phases.setup]
nixPkgs = [
    "python311",
    "gcc"
]

[phases.install]
cmds = [
    "python -m ensurepip --upgrade",
    "python -m pip install --upgrade pip",
    "python -m pip install -r requirements.txt",
    "python -m pip install -e ."
]

[phases.build]
cmds = ["true"]

[start]
cmd = "uvicorn smartsynch.api.main:app --host 0.0.0.0 --port $PORT"