[phases.setup]
nixPkgs = ['python311', 'python311Packages.pip']

[phases.install]
cmds = ['pip install -r requirements.txt && pip install -e .']

[start]
cmd = "uvicorn smartsynch.api.main:app --host 0.0.0.0 --port $PORT" 