[phases.setup]
nixPkgs = [
    "python311",
    "gcc",
    "binutils"
]

[phases.install]
aptPkgs = [
    "python3-dev",
    "python3-pip"
]

cmds = [
    "python3 -m pip install --no-cache-dir -r requirements.txt"
]

[phases.build]
cmds = ["true"]

[start]
cmd = "python3 -m uvicorn smartsynch.api.main:app --host 0.0.0.0 --port $PORT"