services:
  - type: web
    name: smartsynch-ml
    env: python
    buildCommand: |
      cd ml-training/SmartSynch && \
      pip install -r requirements.txt && \
      pip install -e .
    startCommand: uvicorn ml-training.SmartSynch.smartsynch.api.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.10
      - key: HUGGINGFACE_TOKEN
        sync: false