services:
  - type: web
    name: smartsynch-ml
    env: python
    rootDirectory: ml-training/SmartSynch
    buildCommand: |
      echo "Current directory: $(pwd)"
      echo "Listing directory contents:"
      ls -la
      echo "Upgrading pip..."
      python -m pip install --upgrade pip
      echo "Installing requirements..."
      if [ -f "requirements.txt" ]; then
        echo "requirements.txt found"
        cat requirements.txt
        pip install -r requirements.txt
      else
        echo "ERROR: requirements.txt not found!"
        exit 1
      fi
      echo "Installing package..."
      pip install -e .
    startCommand: uvicorn smartsynch.api.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.10
      - key: HUGGINGFACE_TOKEN
        sync: false