services:
  - type: web
    name: smartsynch-ml
    env: python
    rootDirectory: ml-training/SmartSynch
    buildCommand: |
      echo "Current directory: $(pwd)"
      echo "Listing directory contents:"
      ls -la
      echo "Installing requirements..."
      pip install -r requirements.txt
      pip install -e .
    startCommand: uvicorn smartsynch.api.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.10