[phases.setup]
nixPkgs = [
    "python311",
    "gcc",
    "python311Packages.pip",
    "python311Packages.setuptools",
    "python311Packages.wheel"
]

[phases.build]
cmds = [
    "python -m ensurepip --upgrade",
    "python -m pip install --upgrade pip setuptools wheel",
    "ln -sf /usr/bin/python3 /usr/bin/python",
    "ln -sf /usr/bin/pip3 /usr/bin/pip"
]

[phases.install]
cmds = [
    "python3 -m pip install --no-cache-dir -r requirements.txt"
]

[start]
cmd = "python3 -m uvicorn smartsynch.api.main:app --host 0.0.0.0 --port $PORT"