[phases.setup]
aptPkgs = ["python3", "python3-pip", "python3-dev", "gcc", "g++"]

[phases.install]
cmds = ["python3 -m pip install -r requirements.txt"]

[start]
cmd = "python3 -m uvicorn smartsynch.api.main:app --host 0.0.0.0 --port $PORT"