[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"
buildCommand = ""

[deploy]
startCommand = ""
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[env]
PORT = "8000"