services:
  - type: web
    name: smartsynch-ml
    env: python
    buildCommand: |
      python -m pip install --upgrade pip && \
      cd ml-training/SmartSynch && \
      pip install -r requirements.txt && \
      pip install -e .
    startCommand: |
      cd ml-training/SmartSynch && \
      python app.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.9
      - key: REDIS_HOST
        value: ${REDIS_HOST}
      - key: REDIS_PORT
        value: "6380"