services:
  - type: web
    name: smartsynch-ml
    env: python
    buildCommand: |
      python -m pip install --upgrade pip && \
      cd ml-training && \
      pip install -e SmartSynch/
    startCommand: |
      cd ml-training/SmartSynch && \
      python -m uvicorn app:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.9
      - key: REDIS_HOST
        value: ${REDIS_HOST}
      - key: REDIS_PORT
        value: "6380"