services:
  - type: web
    name: smartsynch-ml
    env: python
    buildCommand: pip install -r requirements.txt && pip install -e .
    startCommand: uvicorn smartsynch.api.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.9
      - key: REDIS_HOST
        value: ${REDIS_HOST}
      - key: REDIS_PORT
        value: "6380"