services:
  api:
    build:
      context: ..
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ../models:/app/models
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6380
    depends_on:
      - redis

  redis:
    image: redis:6-alpine
    ports:
      - "6380:6379"
    volumes:
      - redis_data:/data

volumes:
  redis_data: 